/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "nagnnlhxrpfgrrjptmcl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hZ25ubGh4cnBmZ3JyanB0bWNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY4MjI2OTUsImV4cCI6MjA4MjM5ODY5NX0.QlKNsi4QLEHMLwg-ho1HJ7-Q2pKsyeR-Pkz3FMOIRpc"